<style>
    /*body.bug-report-index-index .klloom-title-wrapper .page-title {
        color: #fff;
        margin-bottom: 0;
    }

    body.bug-report-index-index .related-page-links a {
        color: #fff;
    }

    body.bug-report-index-index .klloom-title-wrapper .page-title span {
        color: #35a8e0
    }

    body.bug-report-index-index .klloom-title-wrapper {
        max-width: 1240px;
        margin: auto;
        padding: 0 20px 0;
    }

    body.bug-report-index-index .klloom-content-wrapper {
        max-width: 1240px;
        margin: auto;
        padding: 0 20px 0;
    }

    body.bug-report-index-index .page-title-wrapper,
    body.bug-report-index-index form.form.bug {
        width: 650px;
    }

    body.bug-report-index-index .page-title-wrapper h1 {
        margin-bottom: 0;
    }

    body.bug-report-index-index form.form.bug {
        margin: auto;
        border-left: solid 1px #c6c6c5;
        border-right: solid 1px #c6c6c5;
        padding-bottom: 10px;
    }*/
</style>

<div class="mdl-cell--hide-phone">
    <div class="klloom-content-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing" style="min-height: 410px;">
            <div class="mdl-cell mdl-cell--7-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-cell--middle">
                <p style="font-size: 48px;line-height: 65px;color: #35a8e0">We will be always in beta.</p>
                <p style="color: #b8b8b8; font-size: 24px">Klloom doesn’t intend to be perfect. Admiting our weaknesses and faults make us stronger, as we evolve together with a community of users who participate actively as real curators of our service. Everyone is invited to be part of this movement, and we will stay always open to ideas that may improve our model. We are in Beta, and so we will always be.</p>
            </div>
            <div class="mdl-cell mdl-cell--3-col-desktop mdl-cell--hide-tablet mdl-cell--hide-phone mdl-cell--2-offset-desktop mdl-cell--middle mdl-typography--text-center">
                <img src="<?php echo $this->getViewFileUrl('Klloom_Pages::images/about-graphic-04.svg'); ?>" style="width: 200px"/>
            </div>
        </div>
    </div>
    <div class="klloom-hr"></div>
</div>