<?php
/**
 * Created by PhpStorm.
 * User: yeremiloli
 * Date: 19/09/18
 * Time: 19:56
 */

$product_id = $block->getCurrentProduct()->getId();

$_helperW     = $this->helper('Webkul\Marketplace\Helper\Data');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$image        = 'new_products_content_widget_grid';

$sellerId           = '';
$marketplaceProduct = $_helperW->getSellerProductDataByProductId($product_id);
foreach ($marketplaceProduct as $value) {
    $sellerId = $value['seller_id'];
}

$rowsocial = $_helperW->getSellerDataBySellerId($sellerId);
$shoptitle = '';
$avatar    = $this->getViewFileUrl('images/avatar/no-image.svg');
foreach ($rowsocial as $value) {
    $shoptitle = $value['shop_title'];
    if (!$shoptitle) {
        $shoptitle = $value->getShopUrl();
    }
    if ($value->getLogoPic()) {
        $avatar = $_helperW->getMediaUrl() . 'avatar/' . $value->getLogoPic();
    }
}
$shoptitle = $block->escapeHtml($shoptitle);
$items     = $this->getProductsByCustomer($sellerId);
?>

<?php if ($items) { ?>
<div class="block widget block-products-list grid" style="width: 100%;">

    <div class="klloom-hr"></div>

    <div class="products-grid grid" style="max-width: 1240px; padding: 0 20px; margin: auto">

        <h3 style="margin: 40px 0 20px 0;display: block;"><span style="color:#b1b1b1">Other photos by</span> <?= $shoptitle ?>:</h3>

        <div class="mdl-grid mdl-grid--no-spacing">
            <?php foreach ($items as $_item):
                $productImage = $_imagehelper->init($_item, $image)->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300, 300)->getUrl();
                ?>
                <div id="<?= $_item->getId(); ?>" class="klloom-grid-item mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--2-col-phone">
                    <div class="product-item-info">
                        <div class="photographer-avatar-wrap">
                            <div class="photographer-avatar">
                                <div>
                                        <span class="mdl-chip mdl-chip--contact">
                                            <span class="mdl-chip__contact background-cover" style="background-image: url('<?= $avatar ?>')"></span>
                                            <span class="mdl-chip__text"><?= $shoptitle ?></span>
                                        </span>
                                </div>
                            </div>
                        </div>

                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                           href="<?= $block->escapeUrl($_item->getProductUrl()) ?>"
                           class="product-item-photo">
                            <img src="<?php echo $productImage; ?>"/>
                            <span class="photo-title"><?= $block->escapeHtml($_item->getName()) ?></span>
                        </a>
                        <div class="product-item-details">
                            <?= $block->getProductCommentLikeHtml($_item) ?>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>
<?php } ?>
