<p>By uploading this image you agree to the terms and conditions outlined in the <a href="<?= $block->escapeUrl($block->getUrl('license-agreement')); ?>" target="_blank" title="Klloom Standard License">Klloom Standard License</a>. Basically:</p>
<hr />
<p><span style="color: #000000">Buyer can</span> copy, modify, distribute and perform the image, even for commercial purposes, all without need of credit or endorsement.</p>
<p><span style="color: #000000">Buyer can not</span> resell the image or make it available for download on other stock image banks; use the image for adult content (NSFW) or in an offensive manner (obscene, rude, difamatory); use the image in products where the primary value lies in the image itself.</p>
<hr />
<p><span style="color: #000000">Seller can</span> sell the same image through other commercial licensing vendors or other stock image banks.</p>
<p><span style="color: #000000">Seller can not</span> make it available for free download on free stock image banks.  </p>