<style>
    .cms-page-view ul > li,
    .cms-page-view ol > li {
        margin-top: 0;
        margin-bottom: 12px;
    }
</style>
<div class="bg-page-gray">
    <div class="klloom-title-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing">
            <div class="mdl-cell mdl-cell--6-col-desktop mdl-cell--4-col-tablet mdl-cell--2-col-phone mdl-cell--middle">
                <h1 class="page-title">Klloom Behavior Guidelines</h1>
            </div>
            <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Klloom_Pages::html/menu.phtml")->toHtml(); ?>
        </div>
    </div>
</div>

<div class="page-sub-menu-horizontal" style="padding-top: 30px">
    <div class="klloom-title-wrapper mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
                <a class="mdl-layout__tab is-active" href="#Intro">Intro</a>
                <a class="mdl-layout__tab" href="#Please do not hate">Please do not hate</a>
                <a class="mdl-layout__tab" href="#Please do not discriminate" title="Please do not discriminate">Please do not discriminate</a>
                <a class="mdl-layout__tab" href="#Please do not promote suicide or self-harm" title="Please do not promote suicide or self-harm">Please do not promote suicide or self-harm</a>
                <a class="mdl-layout__tab" href="#Please do not post pornography" title="Please do not post pornography">Please do not post pornography</a>
                <a class="mdl-layout__tab" href="#Please do not post personal information of others" title="Please do not post personal information of others">Please do not post personal information of others</a>
                <a class="mdl-layout__tab" href="#Please do not spam" title="Please do not spam">Please do not spam</a>
                <a class="mdl-layout__tab" href="#Please do not use bots" title="Please do not use bots">Please do not use bots</a>
                <a class="mdl-layout__tab" href="#Please do not infringe copyrights" title="#Please do not infringe copyrights">Please do not infringe copyrights</a>
                <a class="mdl-layout__tab" href="#Please do not pretend to be someone else" title="#Please do not pretend to be someone else">Please do not pretend to be someone else</a>
                <a class="mdl-layout__tab" href="#Please do not cheat on usernames" title="Please do not cheat on usernames">Please do not cheat on usernames</a>
                <a class="mdl-layout__tab" href="#Please do not post content that infringes any children's rights" title="Please do not post content that infringes any children's rights">Please do not post content that infringes any children's rights</a>
            </div>
        </header>
    </div>
</div>

<div class="klloom-content-wrapper">
    <div class="mdl-grid mdl-grid--no-spacing">
        <div class="static-page mdl-cell mdl-cell--8-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
            <p id="Intro">Klloom is an idea that has love as its seed. We do believe that both people and companies should be born for the good. If you are joining community, Klloom deeply expects you to act like your best self: loving, kind, supportive, open-minded, tolerant, considerate, grateful, warm, happy. So, please, help us to build a lovely, respectful network, by also letting Klloom know when you find users acting in a bad way. You can always hit our Report button to disclose any member. Behavior outside of Klloom guidelines may result in account suspension or permanent removal from our network. We have created a list of good-conduct rules that applies not only to comments and texts, but also to all uploaded images. By using Klloom, you must adhere to these guidelines:</p>

            <h2 id="Please do not hate">1. Please do not hate</h2>
            <p>Klloom doesn't allow any insults, threats or hate speech, including any denigrating comments or photos involving sexual orientation, gender, gender identity, race, religious or political belief, or involving anything else in a disrespectful or violent manner.</p>

            <h2 id="Please do not discriminate">2. Please do not discriminate</h2>
            <p>Please do not post any comment, text or image that may be racist, homophobic, transphobic or discriminatory in any way.</p>

            <h2 id="Please do not promote suicide or self-harm">3. Please do not promote suicide or self-harm</h2>
            <p>Any content that encourages others to kill or harm themselves in any way are definitely not allowed.</p>

            <h2 id="Please do not post pornography">4. Please do not post pornography</h2>
            <p>Any sexually explicit or pornographic content is not allowed. There are many appropriate channels for people to post adult-oriented content, please do not use Klloom for that.</p>

            <h2 id="Please do not post personal information of others">5. Please do not post personal information of others</h2>
            <p>Please do not post others’ personal information without explicit consent from them.</p>

            <h2 id="Please do not spam">6. Please do not spam</h2>
            <p>Klloom doesn’t allow fake tags, fake profiles, deceptive links or anything that try to mislead others about the content you post. Please do not use malware or other misleading codes. Please do not phish or have any fraudulent practice. Please do not act for the sole purpose of leading people to your profile or receiving likes.</p>

            <h2 id="Please do not use bots">7. Please do not use bots</h2>
            <p>Please do not automate. Klloom is a network created for flesh-and-bone people.</p>

            <h2 id="Please do not infringe copyrights">8. Please do not infringe copyrights</h2>
            <p>Infringement on other people’s copyrights and trademarks are obviously not allowed. Please do not post any third party’s content without their previous permission. Please make sure you have the right to post the content you are about to share on Klloom. Please do not post content that violates any governmental law or regulation.</p>

            <h2 id="Please do not pretend to be someone else">9. Please do not pretend to be someone else</h2>
            <p>Please do not impersonate others. You can be many selves, as long as they are yours.</p>

            <h2 id="Please do not cheat on usernames">10. Please do not cheat on usernames</h2>
            <p>Only register a username that you are going to use yourself. Do not register usernames to prevent someone else or companies from using them. Do not register celebrity-related usernames with the intention of selling them. Klloom may reclaim usernames that have not been actively used for a long period of time.</p>

            <h2 id="Please do not post content that infringes any children's rights">11. Please do not post content that infringes any children's rights</h2>
            <p>Please do not post anything inappropriate about minors, whatsoever. Just don’t do that. Thanks.</p>
            <br/><br/>
            <p>If you have something wrong to report, please send an email to <a href="mailto:report@klloom.com" title="report@klloom.com">report@klloom.com</a></p>
        </div>
    </div>
</div>