<style>
    @media (max-width: 839px) and (min-width: 480px) {

        .best .mdl-cell.mdl-cell--4-col-tablet {
            margin: 8px;
            width: calc(33.3333333333% - 16px);
        }

        .best .mdl-cell.mdl-cell--4-col-tablet p {
            padding-right: inherit !important;
            font-size: 15px;
            line-height: 20px !important;
        }
    }

    @media (max-width: 479px) {
        .mdl-typography--text-right p{
            text-align: left;
        }
        p {
            padding-right: inherit !important;
        }
    }
</style>
<div class="page-full-background cause-and-effect-01 bg-page-gray">
    <div class="klloom-title-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing">
            <div class="mdl-cell mdl-cell--8-col-desktop mdl-cell--6-col-tablet mdl-cell--2-col-phone mdl-cell--middle">
                <h1 class="page-title"><span>Cause</span> and Effect <i style="color: #35a8e0; top: 2px;position: relative;" class="icon-donation-klloom"></i></h1>
            </div>
            <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Klloom_Pages::html/menu-about.phtml")->toHtml(); ?>
        </div>
    </div>
</div>

<div class="mdl-cell--hide-phone" style="background: url(<?php echo $this->getViewFileUrl('Klloom_Pages::images/cause-and-effect-connect-people-and-companies.png'); ?>) no-repeat right center">
    <div class="klloom-content-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing" style="margin-bottom: 52px; margin-top: 60px; min-height: 410px;">
            <div class="mdl-cell mdl-cell--7-col-desktop mdl-cell--4-col-tablet mdl-cell--7-col-phone mdl-cell--middle">
                <p style="font-size: 65px;line-height: 65px;color: #b8b8b8">We want to connect people and companies in an organic and functional symbiosis.</p>
            </div>
        </div>
    </div>
</div>
<div class="mdl-cell--hide-desktop mdl-cell--hide-tablet" style="padding-top: 60px; padding-bottom: 60px ">
    <div class="klloom-content-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing" style="margin-top: 60px;">
            <div class="mdl-cell mdl-cell--7-col-desktop mdl-cell--4-col-tablet mdl-cell--7-col-phone">
                <p style="font-size: 45px;line-height: 45px;color: #b8b8b8">We want to connect people and companies in an organic and functional symbiosis.</p>
            </div>
        </div>
    </div>
    <div>
        <img src="<?php echo $this->getViewFileUrl('Klloom_Pages::images/cause-and-effect-connect-people-and-companies.png'); ?>"/>
    </div>
</div>

<div class="klloom-hr"></div>

<div class="klloom-content-wrapper">
    <div class="best mdl-grid mdl-grid--no-spacing" style="font-size: 16px;color: #757474;padding-top: 75px;padding-bottom: 75px;">
        <div class="mdl-cell mdl-cell--4-col-desktop mdl-cell--4-col-tablet mdl-cell--4-col-phone">
            <p style="padding-right: 50px">
                Klloom, whose name comes from "darK smaLL rOOM", is designed to be more than a simple place to buy and sell images, we want to be an example of honest and 100% transparent web business, providing a new income alternative and generating a powerful social contribution mechanism. <span style="color: #35a8e0">So think of that archived photo of yours and how it can now be widely shared for such a great purpose.</span>
            </p>
        </div>
        <div class="mdl-cell mdl-cell--4-col-desktop mdl-cell--4-col-tablet mdl-cell--4-col-phone">
            <p style="padding-right: 50px">
                <span style="color: #35a8e0">We are all creators of content, and whether it is in a drawer or in an old pen drive, we can have a unique and true image that can connect and cheer people, generate profit, emerge talents and benefit thousands of humans around the world through our partnerships with charities such as the Red Cross.</span> We want to build a community of users who participate actively as curators of our service and of all our content.
            </p>
        </div>
        <div class="mdl-cell mdl-cell--4-col-desktop mdl-cell--4-col-tablet mdl-cell--4-col-phone">
            <p style="padding-right: 50px">
                Together we can constantly evolve and show the world what the collective is capable of doing. <span style="color: #35a8e0">We invite everyone to be part of this socioeconomic movement, and we will stay always open to ideas that may improve our model. We are and will always be in Beta.</span>
                <br/><br/>
                <i style="color: #35a8e0; font-size: 28px" class="icon-like-active-klloom"></i>
                <br/>
                Best,<br/>Klloom Team
            </p>
        </div>
    </div>
</div>

<div class="klloom-hr"></div>

<div class="klloom-content-wrapper">
    <div class="mdl-grid mdl-grid--no-spacing" style="padding-top: 63px;padding-bottom: 73px;">
        <div class="mdl-cell mdl-cell--4-col-desktop mdl-cell--3-col-tablet mdl-cell--4-col-phone mdl-cell--bottom">
            <img src="<?php echo $this->getViewFileUrl('Klloom_Pages::images/cause-and-effect-20-percent.png'); ?>" style="height: 250px;"/>
        </div>
        <div class="mdl-cell mdl-cell--7-col-desktop  mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-cell--1-offset-desktop mdl-cell--1-offset-tablet mdl-typography--text-right mdl-cell--bottom">
            <p style="font-size: 23px;line-height: 30px;">Let’s be honest. Rethinking the world’s economy model is even more urgent than rethinking the stock photo market. We do believe in a world where corporations can monetize their business while making a difference for the future of our planet, far beyond all bullshit. Twelve percent of all Klloom’s photo licensing incomes goes to our donation partners, which makes Klloom the world's first tangible web initiative that carries a social compromise as an intrinsic part of its core business.</p>
        </div>
    </div>
</div>

<div class="page-full-background cause-and-effect-02 bg-page-gray">
    <div class="klloom-content-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing" style="height: 450px">
            <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-cell--middle mdl-typography--text-center">
                <img title="Pro Natura International" src="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getViewFileUrl('images/logos/logo-pro-natura-international.png')); ?>" style="width: 190px" /> <br />
                <img title="Red Cross" src="<?php echo $this->getViewFileUrl('Klloom_Pages::images/logo-red-cross.svg'); ?>"/>
                <h2 style="display: block; color: #fff">Our first donation partners.</h2>
            </div>
        </div>
    </div>
</div>

<div class="klloom-content-wrapper">
    <div class="mdl-grid mdl-grid--no-spacing" style="padding-top: 85px;padding-bottom: 35px;">

        <div class="mdl-cell mdl-cell--5-col-desktop mdl-cell--5-col-tablet mdl-cell--5-col-phone mdl-cell--middle">
            <p style="font-size: 23px;line-height: 30px; color: #b8b8b8">
                We are happy that Pro-Natura International and Brazilian Red Cross São Paulo widely welcomed our dream of a new business model. Klloom’s first donations will be send to their PayPal account, and all the numbers will be transparently published here on a regular basis.
            </p>
        </div>

        <div class="mdl-cell mdl-cell--6-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone mdl-cell--1-offset-desktop mdl-cell--1-offset-tablet mdl-cell--middle mdl-typography--text-right">
            <img title="Pro Natura" src="<?= /* @escapeNotVerified */ $block->escapeUrl($block->getViewFileUrl('images/logos/logo-pro-natura.png')); ?>" style="height: 100px;" />
            <img title="Red Cross Brazil" src="<?php echo $this->getViewFileUrl('Klloom_Pages::images/logo-red-cross-brazil.svg'); ?>" style="height: 80px;margin-left: 30px; margin-bottom: 10px" />
        </div>
        <div class="mdl-cell mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
            <br/>
            <p>If you are from a Global Humanitarian Organization and want to be part of our donation chain, please send an email to <a href="mailto:donation@klloom.com" title="donation@klloom.com">donation@klloom.com</a>.</p>
        </div>
    </div>
</div>

<div class="klloom-hr"></div>

<div class="mdl-grid mdl-grid--no-spacing" style="height: 480px; padding-top: 50px; padding-bottom: 60px">
    <div class="mdl-cell mdl-cell--12-col mdl-cell--middle mdl-typography--text-center">
        <img style="display: inline-block" src="<?php echo $this->getViewFileUrl('Klloom_Pages::images/backgrounds/history-of-photography-camera-01.png'); ?>"/>
    </div>
</div>