<style>
    .cms-page-view ul > li,
    .cms-page-view ol > li {
        margin-top: 0;
        margin-bottom: 12px;
    }
</style>
<div class="page-full-background how-it-works-01 bg-page-gray">
    <div class="klloom-title-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing">
            <div class="mdl-cell mdl-cell--8-col-desktop mdl-cell--6-col-tablet mdl-cell--2-col-phone mdl-cell--middle">
                <h1 class="page-title"><span>Klloom</span> > Frequently Asked Questions</h1>
            </div>
            <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Klloom_Pages::html/menu-about.phtml")->toHtml(); ?>
        </div>
    </div>
</div>


<div class="klloom-content-wrapper">
    <div class="mdl-grid mdl-grid--no-spacing">
        <div class="static-page mdl-cell mdl-cell--8-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
            <h2 style="margin-top: 80px">What does the name Klloom mean?</h2>
            <p>The name Klloom comes from “darK smaLL rOOM”, which is related to the origin of photography, when the so-called pinhole cameras were made with a closed chamber (camera obscura) containing a small hole without lens. The use of the small and dark room was also present in the process of developing films, when it was necessary to isolate them in a lightproof space.</p>
            <p>Like Klloom's name, our logo was also inspired by photography, and more directly by the optical process that happens at the light input of a pinhole camera.</p>

            <h2>Can I license my photos on Klloom without donating?</h2>
            <p>Fortunately not. :) Donation is an essential part of this community. We do believe in new ways of generating and sharing wealth.</p>

            <h2>Why all the donation is sent to the Red Cross only?</h2>
            <p>Klloom is the world's first tangible initiative that carries a social compromise as an intrinsic part of its core business, and choosing trustworthy Humanitarian Cause organizations is essential for us to guarantee the reliability of our model.</p>
            <p>The Red Cross, one of the largest independent social assistance movements on the planet, is our first humanitarian cause partner, but we do want to have other great organisations to be part of this dream. It’s a matter of time.</p>
            <p>If you are from a Global Humanitarian Organization and want to be part of our donation chain, please send an email to <a href="mailto:donation@klloom.com" title="donation@klloom.com">donation@klloom.com</a>.</p>

            <h2>Is Klloom an NGO (Non-governmental Organization)?</h2>
            <p>No, it isn't. We just want to be an example of honest and sincere business that, besides being a business, also provide a new income alternative for photo lovers and generate a powerful social contribution mechanism.</p>

            <h2>Is Klloom a Red Cross initiative?</h2>
            <p>No, it isn't. Klloom is a private, commercial company with an intrinsic social goal. We are not commercially associated (by law) to any Organization or Institute, even though our business backbone includes connecting to Global Humanitarian Organizations to which we donate part of our incomes. Red Cross is our first donation partner, which means that 20% of our gross licensing incomes are donated to them.</p>

            <h2>Can I sell my photos on Klloom and on other websites at the same time?</h2>
            <p>Yes, you can sell your image through other commercial licensing vendors, or directly to commercial buyers. But your image must not be available on any free stock image bank (such as Pexels or Unsplash). Besides, since Klloom’s photos have an intrinsic social purpose involved, we would be very grateful if you chose photos from your collection exclusively for licensing on Klloom.</p>

            <h2>Why is PayPal the only payment method offered?</h2>
            <p>For your security and privacy, Klloom won't keep any credit card information of its users, as well as their address information. If you are buying a photo, you will be redirected to a secure payment environment outside of Klloom after the checkout, where you will be asked to enter your PayPal login information. So far, PayPal is the more suitable payment platform for Klloom users to avoid sharing extra personal information with us. However, we do consider having other payment methods available in the near future, as long as they allow users to carry on with the payment process outside of Klloom.</p>

            <h2>Does Klloom also offers monthly or annual subscriptions?</h2>
            <p>Not yet. For now, we need to test our codes and business model in a simpler way. We think it may be possible in the future, though. It’s just a start.</p>

            <h2>Does Klloom curate and approve the photos before they are published?</h2>
            <p>No, we don't curate the photos beforehand. Instead, Klloom trusts and depends on its user community’s wisdom and reasonableness to identify, judge, rate and report the content that may be inappropriate, offensive or not in accordance with our Terms and our Behavior Guidelines.</p>
            <p>You can always hit our Report button to disclose any member. Behavior outside of Klloom guidelines may result in account suspension or permanent removal from our network. We have created a list of good-conduct rules that applies not only to comments and texts, but also to all uploaded images. By using Klloom, you must adhere to these guidelines.</p>

            <h2>Can I upload illustrations and graphic design content?</h2>
            <p>Currently, Klloom is not accepting illustration, painting and graphic design content for licensing on the website. We are a photography licensing platform.</p>

            <h2>How should I proceed in case of my photo being reported?</h2>
            <p>Those who had their content removed or made inaccessible in response to a notice of infringement may provide Klloom with a counter notice in writing to <a href="mailto:legal@klloom.com" title="legal@klloom.com">legal@klloom.com</a> if they feel that their content is not infringing. Please include in your counter notice enough information to enable Klloom to make a reasonable resolution. You must note that you may be held responsible for damages (including costs and attorneys' fees) for giving a false account that your content is not infringing any terms or behavior guidelines.</p>

            <h2>How many times can I download the photo after paying for its license?</h2>
            <p>You can download the photo you bought unlimited times while it's available for licensing on the website. We do recommend, though, that you download your file as soon as it appears in the My Purchased Photos in your user settings page. Please keep your own backup of the file as it may become not available for licensing in the future. The download link goes accessible soon after your payment is confirmed.</p>
            <p>Once you downloaded it, there is no expiration or end date on your rights to use the image.</p>

            <h2>Who, besides me, can use the photo after I downloaded it?</h2>
            <p>The license is granted to one person (including a company employee). Additional licenses must be obtained for each member of your organization or company who will use the image.</p>
            <p>There are two exceptions, though:</p>
            <ol type="a">
                <li><span style="color: #000">Employer or Client.</span> In the case you are purchasing the photo on behalf of your employer or client, then your employer or client is allowed to use the image, as long as you state and guarantee that you have full legal authority to bind your employer or client to our Terms of License. If you do not have that permission, then your employer or client must not use the photo.</li>
                <li><span style="color: #000">Subcontractors.</span> In the case of any production or distribution process related to your final project or final use, subcontractors (for instance, a printer or retouching studio) or distributors are allowed to use the image. However, these subcontractors and distributors must not use the photo for purposes other than those mentioned above.</li>
            </ol>
            <p>We’ve been thinking carefully about having a reasonable pricing practice, with the intention of making image licensing accessible to a wider public. Having a Single User license help us to maintain lower prices. Let us know your thoughts about it.</p>

            <h2>I think that 40% of license fee for authors is not fair. Why don’t you raise it?</h2>
            <p>Well, we’ve been working hard to build a trustworthy image bank, and that includes thinking about what would be a fair profit distribution and royalty rate practice, considering that the donation is an essential part of our model.</p>
            <p>One of our biggest challenges is to make the photo licensing process more simple and accessible, and it includes a simple and reasonable pricing.</p>
            <p>Think of it, everyone has at least one great photo archived somewhere in a hard drive; there are billions of great iPhone shots that are just kept in monthly backups, and they would probably never be turned into money at all, neither in delight for photo lovers eyes!</p>
            <p>So, what about turning “nothing" into a 20-dollar photo that will earn you 40% of the fee for each license sold and, still more, generating a compulsory contribution of 20% directly to a humanitarian cause! Doesn’t it sound great enough?</p>
            <p>Initially, licensing your photos at Klloom will earn you 40% royalties out of the gross profit on every Standard License sold. We assure you this rate won’t be reduced, and we do consider raising that in the future. But, before that, we need to look at the big picture. It’s not only about earning some money, it’s about striving to prove that it is possible to have an economic model where monetization and social altruism can walk together.</p>

            <h2>Why am I asked to enter a PayPal email?</h2>
            <p>You are asked to provide a valid PayPal email address just in order to be able to receive payments related to your license fees. Klloom does not ask you to enter your PayPal password. For your security and privacy, we don't keep any credit card information of our users. If you are buying a photo, you will be redirected to a secure payment environment outside of Klloom after the checkout, where you will be asked to enter your PayPal login information.</p>

            <h2>When should I mark my photo as “Editorial Use Only”?</h2>
            <p>Images marked "Editorial Use Only” add an exception to the Klloom Standard License.</p>
            <p>When you mark your photo as "Editorial Use Only" you are saying that it is not allowed to be used for any commercial purpose, including promotional, endorsement, advertorial, advertising or merchandising purpose.</p>
            <p>You should (probably) mark your photo as Editorial Use Only if:</p>
            <ol>
                <li>You are a celebrity, public figure or fashion model, and you appears in the photo.</li>
                <li>You haven’t been authorized by all models and/or properties owners/representatives that appears or have their property depicted in your photo with a valid Release.</li>
                <li>You don’t want your photo to be used for commercial purposes (for whatever reason).</li>
            </ol>

            <h2>Why just three options of price for photographers to choose from?</h2>
            <p>One of our biggest challenges is to make the photo licensing process more simple and accessible, and it includes a simple and reasonable pricing.</p>
            <p>Even though Klloom does think of having a wider range of pricing options in the near future, we need to make it simple for now.</p>

            <br/><br/>
            <p>Do you have a different question? Please <a href="/contact" title="Contact Us">Contact Us</a></p>
        </div>
    </div>
</div>