<style>
    .cms-page-view ul > li,
    .cms-page-view ol > li {
        margin-top: 0;
        margin-bottom: 12px;
    }
</style>
<div class="bg-page-gray">
    <div class="klloom-title-wrapper">
        <div class="mdl-grid mdl-grid--no-spacing">
            <div class="mdl-cell mdl-cell--6-col-desktop mdl-cell--4-col-tablet mdl-cell--2-col-phone mdl-cell--middle">
                <h1 class="page-title">Klloom Privacy Policy</h1>
            </div>
            <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Klloom_Pages::html/menu.phtml")->toHtml(); ?>
        </div>
    </div>
</div>

<div class="page-sub-menu-horizontal" style="padding-top: 30px">
    <div class="klloom-title-wrapper mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
                <a class="mdl-layout__tab is-active" href="#Intro" title="Intro">Intro</a>
                <a class="mdl-layout__tab" href="#Klloom Warranties" title="Klloom Warranties">Klloom Warranties</a>
                <a class="mdl-layout__tab" href="#Knowing Your Rights" title="Knowing Your Rights">Knowing Your Rights</a>
                <a class="mdl-layout__tab" href="#Data Klloom Collects" title="Data Klloom Collects">Data Klloom Collects</a>
                <a class="mdl-layout__tab" href="#We are a Public Platform" title="We are a Public Platform">We are a Public Platform</a>
                <a class="mdl-layout__tab" href="#Communications" title="Communications">Communications</a>
                <a class="mdl-layout__tab" href="#Sharing Your Information" title="Sharing Your Information">Sharing Your Information</a>
                <a class="mdl-layout__tab" href="#Payment Process" title="Payment Process">Payment Process</a>
                <a class="mdl-layout__tab" href="#Cookies" title="Cookies">Cookies</a>
                <a class="mdl-layout__tab" href="#Data Storage" title="Data Storage">Data Storage</a>
                <a class="mdl-layout__tab" href="#Your Choices and Controls" title="Your Choices and Controls">Your Choices and Controls</a>
                <a class="mdl-layout__tab" href="#People Under 18 Years of Age" title="People Under 18 Years of Age">People Under 18 Years of Age</a>
                <a class="mdl-layout__tab" href="#Changes to This Privacy Policy" title="Changes to This Privacy Policy">Changes to This Privacy Policy</a>
                <a class="mdl-layout__tab" href="#Contact Information" title="Contact Information">Contact Information</a>
            </div>
        </header>
    </div>
</div>

<div class="klloom-content-wrapper">
    <div class="mdl-grid mdl-grid--no-spacing">
        <div class="static-page mdl-cell mdl-cell--8-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
            <p id="Intro">Klloom was created to be a glass box brand, which means we have nothing to hide. Nothing. Outsiders can clearly see inside Klloom: our people, our values, our culture, our processes, our dreams, our limits, our fears, and even our mistakes. We do intend to have an open and frank dialogue with our community and with all the society, always sharing our thoughts and plans about the company we want to be. So, as you see, being a glass box is all about transparency, and it’s with data transparency that we want to deal with privacy management. The document below explains Klloom's privacy practices, and what information we collect when you use our website. We do recommend that you read the entire document. Knowing about how, why and when your personal data is used will help you make better choices now and in the future.</p>
            <p style="color:#999999;font-size: 1.1rem;line-height: 18px;">This Privacy Policy covers Klloom's management and treatment of the user's information that Klloom collects and process when you are on the Klloom website and when you use any Klloom service. This policy does not apply to the practices of third parties that Klloom does not own or control, such as Google and Paypal, or to individuals that Klloom does not employ or manage. Occasionally, Klloom may develop and offer new features or services. If the introduction of these new features or services results in any change to the way we collect or process your personal data, we will provide you with more information and additional terms or policies. Unless stated otherwise when we introduce these new features or services, they will be subject to this Privacy Policy.</p>

            <h2 id="Klloom Warranties">Klloom Warranties</h2>
            <p>Klloom will never:</p>
            <ol type="a">
                <li>display paid advertising;</li>
                <li>sell or rent member data to third parties.</li>
            </ol>


            <h2 id="Knowing Your Rights">Knowing Your Rights</h2>
            <p>A new European Union law, called General Data Protection Regulation (GDPR), gives specific rights to internet users in relation to their personal data. As available and except as limited under applicable law, the rights afforded to users are:</p>
            <ol type="a">
                <li><span style="color: #f19106">Right of Access</span>: the right to be informed of and request access to the personal data we process about you.</li>
                <li><span style="color: #f19106">Right to Rectification</span>: the right to request that we amend or update your personal data where it is inaccurate or incomplete.</li>
                <li><span style="color: #f19106">Right to Erasure</span>: the right to request that we delete your personal data.</li>
                <li><span style="color: #f19106">Right to Restrict</span>: the right to request that we temporarily or permanently stop processing all or some of your personal data.</li>
                <li><span style="color: #f19106">Right to Object</span>:
                    <ul>
                        <li>the right, at any time, to object to us processing your personal data on grounds relating to your particular situation;</li>
                        <li>the right to object to your personal data being processed for direct marketing purpose.</li>
                    </ul>
                </li>
                <li><span style="color: #f19106">Right to Data Portability</span>: the right to request a copy of your personal data in electronic format and the right to transmit that personal data for use in another party’s service.</li>
                <li><span style="color: #f19106">Right Not to Be Subject to Automated Decision-Making</span>: the right to not be subject to a decision based solely on automated decision making, including profiling, where the decision would have a legal effect on you or produce a similarly significant effect.</li>
            </ol>

            <h2 id="Data Klloom Collects">Data Klloom Collects</h2>
            <p>Klloom only collects the User data that you share with us on your Settings page, in your photo posts and in your comments, such as Account Type, Name, Email Address, Location, and Photo Descriptions, for example.</p>
            <p>All other Website usage data we collect is general, non-identifiable and inputted anonymously, which may include information about what pages of Klloom you access, how long you stay on Klloom, your current general geographic location (e.g., a city or country, but not a street address), the device you are using, its operating system, an anonymized version of your IP address, and the address of web sites that transfer you to Klloom Website. Klloom also stores your email address and User ID that you choose when you register for an account. That anonymized usage data is utilized to help diagnose problems with Klloom servers, and to evaluate and enhance Klloom's features and performance.</p>
            <p>Klloom may also use this information to protect Klloom and its Users from viruses, spam, to identity theft, illegal or harmful events, and to understand how people use the Site, which services work and which don’t, and which features perform better.</p>
            <p>Klloom uses Google Analytics to collect and process general, anonymous information about user behavior. Google may use this information in order to analyze how you use the site, producing reports about our site activity and providing other services relating to site usage. Even though Klloom is neither responsible for, nor in control of that, Google may also transfer this information to third parties when required by law, or when those third parties process the information on Google’s behalf. With the introduction of the General Data Protection Regulation (GDPR), Google has updated the company’s Privacy Policy to comply with it across all of its services, detailing exactly how and why Google collects the data that powers its various products. As far as we are able to know, the information gathered by Google on Klloom’s behalf is collected in such a way that neither Klloom, nor Google, can easily track saved information back to any individual user. However, Klloom
                encourages all Users to read Google’s Privacy Policy to be fully aware of Google’s procedures regarding personal data. We do believe that it is User's right and obligation to demand for transparency across all information processing chain.</p>
            <p>Bellow you can find a summary of the categories of data Klloom may collect:</p>
            <ol type="a">
                <li>Account Registration. This is the personal data that you provide to enable you to sign up for and use the Klloom Website. This includes your email address (connected to a PayPal account), first name and surname. The data informed on Registration is the minimal personal information necessary for Klloom to provide its services to you. At the end of the Registration Form, you can also opt for (or opt out of) receiving Klloom Newsletters.</li>
                <li>User Profile. In order to allow you to express yourself beyond the basic information collected during registration, we enable you to provide additional information, such as your social media account names, your birthday, a bio, personal website, and instant messaging IDs, as well as to choose to include photos of yourself in your profile. You can always control how your information is displayed and used in your Privacy Settings page.</li>
                <li>Automatic Information. Klloom may collect and store some categories of information whenever you interact with the Website. We may automatically receive and record those "traffic data" on our server logs from your browser, including your IP address, Klloom cookie information, and the page you requested. Klloom also may use this traffic data to help identify and fix problems with its servers, analyze trends and manage the website as to offer a better service for you. Besides the "traffic data", we may collect information about the device you're using to access Klloom, its operating system, and device settings such as language and crash data. This information is also used to help Klloom identify and fix problems with the site and analyze trends. In addition, Klloom may store the total counts that a page has been viewed. None of these automatic information processing include either collecting your personal information, or sharing your data with third parties.</li>
            </ol>

            <h2 id="We are a Public Platform">We are a Public Platform</h2>
            <p>Klloom is a network created for uploading, posting, sharing and selling visual content publicly. You should be aware that anything you post or upload on the Site other than private information will be accessed by the public, which includes comments, titles, hashtags and photo descriptions.</p>
            <p>Also note that search engines (like Google) may be able to find and show the content you post in their results. Content you upload may be copied, shared, or re-posted on the Site and on other parts of the internet in ways that you and Klloom can not control, neither identify or interfere with immediately.</p>
            <p>Even though Klloom enable you to remove posted content from your personal account, and also to delete your entire account at once, we may store backups of your content on our servers for an undetermined time, even after it is deleted or after you remove your account, although it will be no longer visible or publicly accessible on Klloom.</p>
            <p>Moreover, be aware that deleting your account or your content doesn’t mean that your content has not been already copied or shared on Klloom by others, and on other parts of the internet by people or services which are not associated with or connected to Klloom.</p>
            <p>That being so, you should take all this facts into consideration when uploading or posting content to our Website.</p>

            <h2 id="Communications">Communications</h2>
            <p>By opening or keeping an account with Klloom, you agree to receive administrative emails as part of your regular service. These administrative emails are necessary for Klloom to send you system messages, such as sign-up and deletion confirmations, system notifications, password reset links, and to inform you about changes in our Terms or Policies, for instance. Besides that, from time to time we may send you Newsletters with information about Klloom, like news, additional features, surveys or articles. You can always opt-out of these Newsletters on your sign-up form, on your Settings Page, and/or by following the “unsubscribe” instructions contained in each email message (at the bottom of the email). However, please acknowledge that in all cases you will continue to receive our administrative emails and legal notices, unless you delete your account.</p>

            <h2 id="Sharing Your Information">Sharing Your Information</h2>
            <p>Klloom does not make money from selling information about our users to third parties, including advertisers, data brokers, search engines, or anyone else. However, since Klloom enables people to discover and share information with one another, information about the people who use our Website is an essential part of our experience. That being so, information Klloom collects during your registration and information you enter into your Settings Page and into your Edit Profile page, such as your full name and location, may be displayed to other users in your User Public Profile.</p>
            <p>Klloom may also share your personal information under the following circumstances:</p>
            <ol type="a">
                <li>If you authorized Klloom to do so.</li>
                <li>If we believe that we need to do so to comply with applicable law or legal obligations, regulations, legal process, governmental request, or governmental order. Klloom will give you advance notice if we are going to release your information unless we are by law prohibited from or advised against doing so.</li>
                <li>If we need to prevent serious harm to Klloom, its users, you, or anyone else. Or if we think that by disclosing your information we may protect the rights, property, or safety of Klloom, our employees, our users, or others. This includes exchanging information with other companies and organizations for fraud and security protection. In these cases, we may do so without notifying you.</li>
            </ol>

            <h2 id="Payment Process">Payment Process</h2>
            <p>For your security and privacy, Klloom does not keep any credit card information of its users. Instead, we rely on third party companies, such as PayPal, to carry on with the checkout process in a secure payment environment outside of Klloom.</p>
            <p>These third party companies may share some of your personal information back with Klloom just in order to allow us to issue the invoice related to your purchase. This personal information includes your name, your billing address and your Taxpayer Identification Number, but will never include the number of your credit card.</p>

            <h2 id="Cookies">Cookies</h2>
            <p>A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyze web traffic and tell how and when pages in our website are visited. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.</p>
            <p>Klloom uses traffic log cookies to identify which pages are being used and by how many people. This helps us analyze data about web page traffic and improve our Website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.</p>
            <p>In addition, we utilize Google Analytics to help analyze how our site is used. This service also use cookies to collect information about visitors to our site (including IP addresses) in an anonymous form that does not include personal information.</p>
            <p>Overall, cookies help us provide you with a better Website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives Klloom access to your computer or collects any personal information.</p>
            <p>Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. However, this may prevent you from taking full advantage of our Website.</p>
            <p>The table below lists the cookies we collect and what information they store.</p>

            <style>
                .mdl-data-table {
                    font-size: 1.3rem;
                }

                .mdl-data-table tr th:first-child,
                .mdl-data-table tr td:first-child {
                    border-right: solid 1px #c6c6c5;

                }
            </style>
            <table class="mdl-data-table mdl-js-data-table mdl-data-table--selectable">
                <thead>
                <tr style="border-bottom: solid 1px #c6c6c5; border-top: solid 1px #c6c6c5">
                    <th class="mdl-data-table__cell--non-numeric">Cookie Name</th>
                    <th>Cookie Description</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">FORM_KEY</td>
                    <td class="mdl-data-table__cell--non-numeric">Stores randomly generated key used to prevent forged requests</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">PHPSESSID</td>
                    <td class="mdl-data-table__cell--non-numeric">Your session ID on the server</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">GUEST-VIEW</td>
                    <td class="mdl-data-table__cell--non-numeric">Allows guests to view and edit their orders</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">PERSISTENT_SHOPPING_CART</td>
                    <td class="mdl-data-table__cell--non-numeric">A link to information about your cart and viewing history, if you have asked for this.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">STF</td>
                    <td class="mdl-data-table__cell--non-numeric">Information on products you have emailed to friends.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">STORE</td>
                    <td class="mdl-data-table__cell--non-numeric">The store view or language you have selected.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">USER_ALLOWED_SAVE_COOKIE</td>
                    <td class="mdl-data-table__cell--non-numeric">Indicates whether a customer allowed to use cookies.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">MAGE-CACHE-SESSID</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates caching of content on the browser to make pages load faster.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">MAGE-CACHE-STORAGE</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates caching of content on the browser to make pages load faster.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">MAGE-CACHE-STORAGE-SECTION-INVALIDATION</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates caching of content on the browser to make pages load faster.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">MAGE-CACHE-TIMEOUT</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates caching of content on the browser to make pages load faster.</td>
                </tr>

                <tr>
                    <td class="mdl-data-table__cell--non-numeric">SECTION-DATA-IDS</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates caching of content on the browser to make pages load faster.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">PRIVATE_CONTENT_VERSION</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates caching of content on the browser to make pages load faster.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">X-MAGENTO-VARY</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates caching of content on the browser to make pages load faster.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">MAGE-TRANSLATION-FILE-VERSION</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates translation of content to other languages.</td>
                </tr>
                <tr>
                    <td class="mdl-data-table__cell--non-numeric">MAGE-TRANSLATION-STORAGE</td>
                    <td class="mdl-data-table__cell--non-numeric">Facilitates translation of content to other languages.</td>
                </tr>
                </tbody>
            </table>

            <h2 id="Data Storage">Data Storage</h2>
            <p>Even though Klloom’s operations are in Brazil, our servers are located in the United States. As a result, regardless of where you live, your content is transferred to and stored in the United States. Therefor, you must acknowledge and agree that Klloom’s servers are in the United States, and you hereby consent to the transfer, processing, and storage of your content in the United States.</p>
            <p>Furthermore, despite all our security measures and procedures to protect your information from unauthorized access, use, or disclosure, you should be aware that unfortunately Klloom cannot entirely remove security risks associated with our stored information.</p>
            <p>In the event of a personal data breach, Klloom will, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to users and to the supervisory authority competent (if it applies), unless the personal data breach is unlikely to result in a risk to the rights and freedoms of our users.</p>

            <h2 id="Your Choices and Controls">Your Choices and Controls</h2>
            <p>Klloom allows users to control the display and use of some of their personal information. We will be frequently adding new features and controls, so please visit your Settings Page as often as possible for configuring your account to suit your preferences about data collection, privacy and data sharing.</p>
            <p>Bellow you can find a summary of the categories of data you can manage and what kind of control or choice you have on them so far:</p>
            <ol type="a">
                <li>General Information. By visiting your Settings Page and your User Profile, you can correct, amend, add or delete personal information on our Website.</li>
                <li>Newsletters. If you do not wish to receive non-administrative emails from Klloom, please visit the Settings Page and hit the option “Newsletters" on the side menu, or follow the “unsubscribe” instructions contained in each email message (at the bottom of the email).</li>
                <li>Download Your Data. If you would like to get a consolidated copy of the personal data of yours Klloom store, you can do this by clicking the Download My Data button in the Privacy Settings section of your account page.</li>
                <li>Photo Visibility. On your Edit Photo page you can choose if your photo is Published (publicly visible) or Private. If you choose to make it Private, your photo will not be accessible to other users.</li>
                <li>Delete Account. You can delete your entire account, including all information related to it, by clicking the Delete Account link on your Settings page. You will receive a confirmation email to proceed with the deletion.</li>
                <li>Using Your Browser to Control Cookies. The majority of browsers enable you to prevent the application from accepting new cookies, to command the browser to tell you when you receive a new cookie, or to fully disable cookies. Please note, however, that if your browser does not accept cookies, you will not be able to take advantage of some of our features.</li>
            </ol>

            <h2 id="People Under 18 Years of Age">People Under 18 Years of Age</h2>
            <p>To be eligible to buy, sell, view, search and collect Visual Content on Klloom, as well as sharing comments, opinions, and "Liking" photos, you must be at least 18 years old. As a result, Klloom does not deliberately collect information about people under 18. Please contact Klloom if you observe that a child or youth under the age of 18 is using the Website, or has posted personal information about themselves on Klloom. We will remove both the information and the child or youth’s Klloom account as quickly as possible.</p>

            <h2 id="Changes to This Privacy Policy">Changes to This Privacy Policy</h2>
            <p>Klloom may update this Privacy Policy regularly. In case we update this Privacy Policy with important changes, we will let you know by sending an email to the address connected with your Klloom account, or notifying you through our website, also indicating when the change will be effective. If you do not agree with the upcoming update, please delete your account. If you continue to use Klloom after the stated operative date, we will assume you accepted the change.</p>

            <h2 id="Contact Information">Contact Information</h2>
            <p>Klloom welcomes any questions or opinions regarding this Privacy Policy. If you have any comments or requests relating to this Privacy Policy, please send an email to <a href="mailto:legal@klloom.com" title="legal@klloom.com">legal@klloom.com</a>.</p>

            <br/><br/>
            <p style="color: #f19106">This Privacy Policy was last updated on September, 2018.</p>

        </div>
    </div>
</div>