<?php
$_helperW     = $this->helper('Webkul\Marketplace\Helper\Data');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$block= $block->getLayout()->createBlock('Klloom\Trending\Block\Data');
//echo $blockObj->getMyCustomMethod();
$items        = $block->getTrendingProducts('all');
$image        = 'new_products_content_widget_grid';
?>

<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_CatalogWidget::product/widget/content/html/menu.phtml")->toHtml(); ?>
<style>
    .klloom-grid .klloom-grid-item .product-item-details .actions-secondary {
        display: inline-block !important;
        /*background: blue;*/
        width: 100%;
        margin: 0;
    }
    .klloom-grid .klloom-grid-item .product-item-details .actions-secondary a {
        display: inline-block;
        height: 18px;
        float: left;
    }
    .klloom-grid .klloom-grid-item .product-item-details .actions-secondary p{
        float: right;
    }
</style>
<div class="block widget block-products-list grid">
    <div class="block-content">
        <?= /* @noEscape */
        '<!-- ' . $image . '-->' ?>
        <div class="products-grid grid">
            <div class="mdl-grid mdl-grid--no-spacing klloom-grid">
                <?php $i = 1;
                if($items){
                foreach ($items as $_item):
                    $productImage = $_imagehelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(300)->getUrl();

                    $seller_id = false;
                    $shoptitle = '';
                    $shopUrl = '';
                    $avatar    = $this->getViewFileUrl('images/avatar/no-image.svg');

                    $marketplaceProduct = $_helperW->getSellerProductDataByProductId((int)$_item->getId());
                    foreach ($marketplaceProduct as $value) {
                        $seller_id = $value['seller_id'];
                    }
                    if ($seller_id) {
                        $rowsocial = $_helperW->getSellerDataBySellerId($seller_id);
                        foreach ($rowsocial as $seller) {
                            if (!empty($seller['shop_title'])) {
                                $shoptitle = '@' . $seller['shop_title'];
                                $shopUrl = $seller['shop_url'];
                            }
                            if ($seller->getLogoPic()) {
                                $logoPic = str_replace('.', '-small.', $seller->getLogoPic());
                                $avatar = $_helperW->getMediaUrl() . 'avatar/thumb' . $logoPic;
                            }
                        }
                    }
                    $columnMP = ''; // ($i % 4 == 0) ? 'lastcolumn' : '';
                    $shop_url = $_helperW->getRewriteUrl('marketplace/seller/profile/shop/' . $shopUrl);
                    ?>
                    <!-- <?php echo $i . ' - ' . $_item->getCreatedAt(); ?> -->
                    <div data-price="<?= $_item->getFinalPrice() ?>" data-license="<?= $_item->getKlloomLicense() ?>" id="<?= $_item->getId(); ?>" class="klloom-grid-item mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--2-col-phone <?= 'license-' . $_item->getKlloomLicense(); ?> <?= 'price-' . $_item->getFinalPrice(); ?> <?= $columnMP ?>">
                        <div class="product-item-info">
                            <div class="photographer-avatar-wrap">
                                <div class="photographer-avatar">
                                    <div>
                                        <a href="<?= $shop_url ?>" class="mdl-chip mdl-chip--contact">
                                            <span class="mdl-chip__contact background-cover" style="background-image: url('<?= $avatar ?>')"></span>
                                            <span class="mdl-chip__text"><?= $shoptitle ?></span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <a title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= $block->escapeUrl($_item->getProductUrl()) ?>" class="product-item-photo">
                                <img src="<?php echo $productImage; ?>"/>
                                <span class="photo-title"><?= $block->escapeHtml($_item->getName()) ?></span>
                            </a>
                            <div class="product-item-details">
                                <?= $block->getProductCommentLikeHtml($_item) ?>
                            </div>
                        </div>
                    </div>
                    <?php $i++; endforeach;
                } ?>
            </div>
        </div>
    </div>
</div>